/* config.h.  FIXME: Generated by autotools.  */
#ifndef CONFIG_H
#define CONFIG_H

/* Define to 1 if you have the 'getenv' function. */
#define HAVE_GETENV 1

/* Define to 1 if you have the 'SDL_mixer' library (-lSDL_mixer). */
#define HAVE_LIBSDL_MIXER 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <SDL_mixer.h> header file. */
#define HAVE_SDL_MIXER_H 1

/* Define to 1 if you have the <SDL/SDL_mixer.h> header file. */
#define HAVE_SDL_SDL_MIXER_H 1

/* Define to 1 if you have the 'setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Name of package */
#define PACKAGE "sdlroids"

/* Version number of package */
#define VERSION "1.4.0"

#endif
